# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20161031_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='meters',
            field=models.IntegerField(blank=True, default=0, help_text='Total meters.', verbose_name='Total meters.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='metersAverage',
            field=models.IntegerField(blank=True, default=0, help_text='Meters average.', verbose_name='Meters average.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='minutes',
            field=models.IntegerField(blank=True, default=0, help_text='Total minutes.', verbose_name='Total minutes.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='minutesAverage',
            field=models.IntegerField(blank=True, default=0, help_text='Minutes average', verbose_name='Minutes average.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='strokes',
            field=models.IntegerField(blank=True, default=0, help_text='Total strokes', verbose_name='Total strokes.'),
        ),
    ]
